// <auto-generated />
using System;
using DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbContext.Migrations.SqlServerDbContext
{
    [DbContext(typeof(MainDbContext.SqlServerDbContext))]
    [Migration("20260901121505_miInitial")]
    partial class miInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbModels.DbAttraction", b =>
                {
                    b.Property<Guid>("AttractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(200)");

                    b.HasKey("AttractionId");

                    b.ToTable("Attraction");
                });

            modelBuilder.Entity("DbModels.DbComment", b =>
                {
                    b.Property<Guid>("CommentsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommentText")
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("DbAttractionAttractionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CommentsId");

                    b.HasIndex("DbAttractionAttractionId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("DbModels.DbComment", b =>
                {
                    b.HasOne("DbModels.DbAttraction", "DbAttraction")
                        .WithMany("DbComments")
                        .HasForeignKey("DbAttractionAttractionId");

                    b.Navigation("DbAttraction");
                });

            modelBuilder.Entity("DbModels.DbAttraction", b =>
                {
                    b.Navigation("DbComments");
                });
#pragma warning restore 612, 618
        }
    }
}
