// <auto-generated />
using System;
using DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbContext.Migrations.SqlServerDbContext
{
    [DbContext(typeof(MainDbContext.SqlServerDbContext))]
    partial class SqlServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbAttractionDbCategory", b =>
                {
                    b.Property<Guid>("DbAttractionsAttractionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DbCategoriesCategoryId")
                        .HasColumnType("int");

                    b.HasKey("DbAttractionsAttractionId", "DbCategoriesCategoryId");

                    b.HasIndex("DbCategoriesCategoryId");

                    b.ToTable("DbAttractionDbCategory");
                });

            modelBuilder.Entity("DbModels.DbAddress", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DbCityCityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DbCountryCountryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AddressId");

                    b.HasIndex("DbCityCityId");

                    b.HasIndex("DbCountryCountryId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("DbModels.DbAttraction", b =>
                {
                    b.Property<Guid>("AttractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DbCityCityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(200)");

                    b.HasKey("AttractionId");

                    b.HasIndex("DbCityCityId");

                    b.ToTable("Attraction");
                });

            modelBuilder.Entity("DbModels.DbCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .HasColumnType("varchar(200)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("DbModels.DbCity", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("DbCountryCountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.HasKey("CityId");

                    b.HasIndex("DbCountryCountryId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("DbModels.DbComment", b =>
                {
                    b.Property<Guid>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommentText")
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("DbAttractionAttractionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.HasKey("CommentId");

                    b.HasIndex("DbAttractionAttractionId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("DbModels.DbCountry", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.HasKey("CountryId");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("DbModels.DbReview", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AttractionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DbUserUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("AttractionId");

                    b.HasIndex("CommentId");

                    b.HasIndex("DbUserUserId");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("DbModels.DbUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(200)");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("DbAttractionDbCategory", b =>
                {
                    b.HasOne("DbModels.DbAttraction", null)
                        .WithMany()
                        .HasForeignKey("DbAttractionsAttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbModels.DbCategory", null)
                        .WithMany()
                        .HasForeignKey("DbCategoriesCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbModels.DbAddress", b =>
                {
                    b.HasOne("DbModels.DbCity", "DbCity")
                        .WithMany()
                        .HasForeignKey("DbCityCityId");

                    b.HasOne("DbModels.DbCountry", "DbCountry")
                        .WithMany()
                        .HasForeignKey("DbCountryCountryId");

                    b.Navigation("DbCity");

                    b.Navigation("DbCountry");
                });

            modelBuilder.Entity("DbModels.DbAttraction", b =>
                {
                    b.HasOne("DbModels.DbCity", null)
                        .WithMany("DbAttractions")
                        .HasForeignKey("DbCityCityId");
                });

            modelBuilder.Entity("DbModels.DbCity", b =>
                {
                    b.HasOne("DbModels.DbCountry", "DbCountry")
                        .WithMany("DbCities")
                        .HasForeignKey("DbCountryCountryId");

                    b.Navigation("DbCountry");
                });

            modelBuilder.Entity("DbModels.DbComment", b =>
                {
                    b.HasOne("DbModels.DbAttraction", "DbAttraction")
                        .WithMany()
                        .HasForeignKey("DbAttractionAttractionId");

                    b.Navigation("DbAttraction");
                });

            modelBuilder.Entity("DbModels.DbReview", b =>
                {
                    b.HasOne("DbModels.DbAttraction", "DbAttraction")
                        .WithMany("DbReviews")
                        .HasForeignKey("AttractionId");

                    b.HasOne("DbModels.DbComment", "DbComment")
                        .WithMany()
                        .HasForeignKey("CommentId");

                    b.HasOne("DbModels.DbUser", "DbUser")
                        .WithMany("DbReviews")
                        .HasForeignKey("DbUserUserId");

                    b.Navigation("DbAttraction");

                    b.Navigation("DbComment");

                    b.Navigation("DbUser");
                });

            modelBuilder.Entity("DbModels.DbAttraction", b =>
                {
                    b.Navigation("DbReviews");
                });

            modelBuilder.Entity("DbModels.DbCity", b =>
                {
                    b.Navigation("DbAttractions");
                });

            modelBuilder.Entity("DbModels.DbCountry", b =>
                {
                    b.Navigation("DbCities");
                });

            modelBuilder.Entity("DbModels.DbUser", b =>
                {
                    b.Navigation("DbReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
